### PR TITLE
Kinase-informed models

### PR DESCRIPTION
**Pull request by t-kimber**
Ensure that the three kinase-informed neural network are running.

### CODE REVIEW

**Comment by t-kimber** [comment]
This PR is ready to be merged :)

**Comment by jchodera** [comment]
@t-kimber It looks like this branch has conflicts that need to be resolved: 
image

Are you able to rebase?

**Review by schallerdavid — APPROVED** [review]
Looks good after resolving the conflicts :)

**Comment by t-kimber** [comment]
@schallerdavid , this PR is now ready! If you approve, please go ahead and merge :)

**Review by schallerdavid — APPROVED** [review]

**Pull request merged**
